merge_imports = true
edition = "2018"

# indent_style = "Visual"

wrap_comments = false
comment_width = 90

format_strings = true

inline_attribute_width = 50

combine_control_expr = false

fn_single_line = true

format_macro_matchers = true
format_macro_bodies = true

force_multiline_blocks = true

newline_style = "Unix"

normalize_comments = true
format_doc_comments = true

reorder_impl_items = true

# TODO: make this viable
# report_todo = "Unnumbered"
# report_fixme = "Unnumbered"

struct_field_align_threshold = 20
use_field_init_shorthand = true

normalize_doc_attributes = true
